### ISSUE TITLE
Issue with plugin on grafana cloud

### ISSUE THREAD

**Issue by ShravanSunder** [Altinity/clickhouse-grafana#517]
There's issues entering the url in grafana cloud.  the url field doesn't update.  if you paste a url and then hit save you get this issue:

![2024-02-21 0225 Brave Browser vertamedia-clickhouse-datasource - Data sources - Connections - Grafana](https://github.com/Altinity/clickhouse-grafana/assets/5294949/da873640-c83c-4a66-93ce-39f67cf4e3da)

```
An unexpected error happened
Details
TypeError: Cannot assign to read only property 'dataSourceUrl' of object '[object Object]'

    at eval (https://askluna.grafana.net/public/plugins/vertamedia-clickhouse-datasource/module.js?_cache=1708546941362:3:3699851)
    at div
    at St (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/Connections.1a1f34941241fd42b978.js:52:2344)
    at r (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/8924.efc75527866d985a6ea7.js:1:171)
    at form
    at At (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/Connections.1a1f34941241fd42b978.js:60:1919)
    at Pt (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/Connections.1a1f34941241fd42b978.js:60:1469)
    at c (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/8924.efc75527866d985a6ea7.js:370:17436)
    at div
    at div
    at div
    at div
    at te (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/8216.ce77ca4ec71fd8010d08.js:320:4617)
    at u (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/8924.efc75527866d985a6ea7.js:194:29825)
    at div
    at B (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/8924.efc75527866d985a6ea7.js:370:21177)
    at Ot (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/Connections.1a1f34941241fd42b978.js:60:4970)
    at Rt (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/Connections.1a1f34941241fd42b978.js:60:5383)
    at k (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/8216.ce77ca4ec71fd8010d08.js:465:29184)
    at k (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/8216.ce77ca4ec71fd8010d08.js:465:31338)
    at Xt (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/Connections.1a1f34941241fd42b978.js:68:2099)
    at Suspense
    at o (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/8924.efc75527866d985a6ea7.js:194:121927)
    at Uo (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/8924.efc75527866d985a6ea7.js:315:9716)
    at k (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/8216.ce77ca4ec71fd8010d08.js:465:29184)
    at _i (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/8216.ce77ca4ec71fd8010d08.js:456:4454)
    at ai (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/8216.ce77ca4ec71fd8010d08.js:456:12004)
    at pt (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/8216.ce77ca4ec71fd8010d08.js:465:17389)
    at k (https://grafana-assets.grafana.net/grafana/10.4.0-66955/public/build/8216.ce77ca4ec71fd8010d08.js:465:31338
```

**Comment by Slach** [comment]
Duplicated with https://github.com/Altinity/clickhouse-grafana/issues/516#issuecomment-1957520967

thanks for reporting

**Comment by Slach** [comment]
tests on 3.0.3 in grafana cloud
